apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop-slave-demo-1
  labels:
    component: hadoop-slave-demo-1
    role: slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hadoop-slave-demo-1
        role: slave
    spec:
      containers:
      - name: hadoop-slave-demo-1
        image: bfd/rdc/hadoop-slave:1.0
        env:
        - name: "CMD"
          value: "nodemanager"
        - name: "HOSTNAME"
          value: "hadoop-slave-demo-1"
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        - containerPort: 8042
          name: web
          protocol: TCP
          hostPort: 18042
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
