apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop
  labels:
    component: hadoop 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hadoop
    spec:
      containers:
      - name: hadoop
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: bfd/rdc/hadoop-master:1.0
        env:
        - name: "CMD"
          value: "resoucemanager"
        ports:
        - containerPort: 8088
          hostPort: 18088
          name: dashboard
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
