apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop-slave
  labels:
    component: hadoop-slave 
    role: slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hadoop-slave
        role: slave
    spec:
      containers:
      - name: hadoop-slave
        image: bfd/rdc/hadoop-slave:1.0
        env:
        - name: "CMD"
          value: "nodemanager"
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
