apiVersion: v1
kind: Service
metadata:
  name: hadoop-slave-demo-1
  labels:
    component: hadoop-slave-demo-1
    role: slave
spec:
  selector:
    component: hadoop-slave-demo-1
  ports:
  - name: http
    port: 45454
    protocol: TCP
