apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
  labels:
    component: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      imagePullSecrets:
      - name: bfdreg
      containers:
      - name: zookeeper
        image: jplock/zookeeper
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}

